import { useQuery } from "@tanstack/react-query";
import type { FeatureCollection, MultiPolygon, Polygon } from "geojson";

/**
 * NLAMS West Bengal 28-district target-state parcel demo (see
 * public/geo/wb_parcels — generated by scripts/convert-wb-parcels.mjs from
 * the source CSVs). `real` marks the 1,272 features captured from actual
 * Banglarbhumi HAR files (Babupur, North 24 Parganas + Gouripur, Bankura);
 * every other feature is a synthetic parcel generated inside a real block
 * boundary and MUST NOT be presented as an authoritative land record.
 */
export interface WbParcelFeatureProperties {
  id: string;
  block: string;
  mouza: string;
  plot: string;
  areaSqm: number;
  real: boolean;
  /** Cadastral record fields carried from the "Modified" NLAMS source CSVs —
   * still demo attribute data, not an authoritative land record. */
  khatianType: string;
  khatianNo: string;
  legalStatus: string;
  landRecordStatus: string;
  mutationStatus: string;
  rorStatus: string;
  landClassification: string;
  currentLandUse: string;
  cropType: string;
  croppingIntensity: string;
  irrigationStatus: string;
  irrigationSource: string;
  governmentLand: boolean;
  ownerCount: number;
  ownershipType: string;
  tenancyStatus: string;
  encumbranceStatus: string;
  litigationStatus: string;
  ownershipVerification: string;
  fieldVerificationStatus: string;
  boundaryVerification: string;
  lastVerifiedDate: string;
}

export type WbParcelFeatureCollection = FeatureCollection<
  Polygon | MultiPolygon,
  WbParcelFeatureProperties
> & { disclaimer: string };

export interface WbParcelManifestEntry {
  slug: string;
  /** District name as captured in the source CSV — already display-ready. */
  district: string;
  parentDistrict: string;
  status:
    | "CURRENT_23_DISTRICT"
    | "CURRENT_PARENT_MINUS_PROPOSED_CARVEOUT"
    | "PROPOSED_DISTRICT_2026_BUDGET"
    | "PROPOSED_REVENUE_DISTRICT_VIEW";
  count: number;
  realCount: number;
}

async function fetchJson<T>(path: string): Promise<T> {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`Failed to load ${path}: ${res.status}`);
  return res.json() as Promise<T>;
}

/** Lightweight per-district counts for the picker — no geometry, so this
 * loads instantly regardless of which district ends up selected. */
export function useWbParcelManifest() {
  return useQuery({
    queryKey: ["geo", "wb-parcels", "manifest"],
    queryFn: () => fetchJson<WbParcelManifestEntry[]>("/geo/wb_parcels/manifest.json"),
    staleTime: Infinity,
  });
}

/** Full parcel geometry for one district — fetched only once a district is
 * actually selected (files run 40KB-3MB; loading all 28 at once would be
 * ~43MB and ~135k polygons). */
export function useWbParcelDistrict(slug: string | null) {
  return useQuery({
    queryKey: ["geo", "wb-parcels", slug],
    queryFn: () => fetchJson<WbParcelFeatureCollection>(`/geo/wb_parcels/${slug}.geojson`),
    enabled: !!slug,
    staleTime: Infinity,
  });
}
